### ISSUE TITLE
Logstash Plugin Routine Fails

### ISSUE THREAD

**Issue by vforgione** [5thColumn/ansible-role-elastic-stack-5.x#11]
Kept running into ruby issues with listing out the installed plugins. My work around for now was to remove that task and the `when` clauses that use its output. and everything worked fine.

**Comment by ajrgrubbs** [comment]
@vforgione I've never encountered this issue myself - does the issue still exist? And can you paste an example of the error message you see?

**Comment by vforgione** [comment]
This was because it was trying to list plugins for a fresh install. I don't have the error output. Also, I'm pretty sure we fixed this with one of the previous PRs.

**Comment by ajrgrubbs** [comment]
Ok - assuming we can close then. Significant work has been done on this role over the past three weeks, not surprised if it's already been addressed.
