### ISSUE TITLE
Kibana - add PID file workaround for systemd

### ISSUE THREAD

**Issue by ajrgrubbs** [5thColumn/ansible-role-elastic-stack-5.x#19]
Previously, a fix was made regarding bad permissions on `/var/run/kibana.pid`, which the "kibana" user needs to be able to create/write. However, this fix (made to `/etc/init.d/kibana`) only worked for Ubuntu 14. In Ubuntu 16, service management switched to Systemd - I believe the file in question is located at `/etc/systemd/system/kibana.service`. A similar fix needs to be provided.

Until we get a workaround for this, restarting kibana requires some manual intervention to provide access to the pid file.

**Comment by dm00000** [comment]
@ajrgrubbs I think you can close this out.

**Comment by ajrgrubbs** [comment]
https://github.com/5thColumn/ansible-role-elastic-stack-5.x/pull/20
